### ISSUE TITLE
Обсудить и нарисовать фрагменты регистрации и логина

### ISSUE THREAD

**Issue by season6** [season6/android-academy-music-player#5]
Придумать как должна выглядеть форма авторизации и логина в нашем приложении.

**Comment by dimyalt** [comment]
Говорят делать как на скрине в основной группе академии
![2021-09-27_10-24-51](https://user-images.githubusercontent.com/84721615/134863030-678a82a5-8635-4848-9633-0f75972cdd5f.png)
![2021-09-27_10-25-56](https://user-images.githubusercontent.com/84721615/134863086-ee07da96-3653-4c09-8cff-200d1f5d25e2.png)
